tools: Add a script to generate YAML for use with `modifyrepo_c` command
When you download the RPM files with `tools/download-rpm.sh` and build a local repository,
installing `groonga-tokenizer-mecab` will result in the following error.

```
No available modular metadata for modular package 'mecab-0.996-2.module_el8.6.0+3340+d764b636.x86_64', it cannot be installed on the system
No available modular metadata for modular package 'mecab-ipadic-2.7.0.20070801-16.module_el8.6.0+3340+d764b636.x86_64', it cannot be installed on the system
Error: No available modular metadata for modular package
```

This error occurs because there is no metadata for the modular repository.
Add a script to generate the YAML required when registering metadata with `modifyrepo_c` command.