pgroonga: remove pgroonga.varchar_array_term_search_ops_v2 operator class (#678)
GitHub: GH-647

This is part of the task of remove "pgroonga" schema. It's deprecated
since PGroonga 2. This is incompatible with PGroonga 3.x or earlier.

---

The result of upgrade test:

```
+ sudo dnf install -y /host/almalinux/9/x86_64/Packages/postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64.rpm
Last metadata expiration check: 0:00:32 ago on Wed Feb  5 05:08:15 2025.
Dependencies resolved.
==========================================================================================================================================================================
 Package                                              Architecture                     Version                               Repository                              Size
==========================================================================================================================================================================
Upgrading:
 postgresql17-pgdg-pgroonga                           x86_64                           4.0.0-1.el9                           @commandline                           775 k

Transaction Summary
==========================================================================================================================================================================
Upgrade  1 Package

Total size: 775 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                  1/1 
  Upgrading        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    2/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    1/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    2/2 

Upgraded:
  postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                           

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE;'
ALTER EXTENSION pgroonga UPDATE;
ALTER EXTENSION
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE memos (
  title text,
  tags varchar(1023)[]
);
CREATE TABLE
INSERT INTO memos VALUES ('PostgreSQL', ARRAY['PostgreSQL']);
INSERT 0 1
INSERT INTO memos VALUES ('Groonga', ARRAY['Groonga']);
INSERT 0 1
INSERT INTO memos VALUES ('PGroonga', ARRAY['PostgreSQL', 'Groonga']);
INSERT 0 1
CREATE INDEX pgroonga_memos_index ON memos
  USING pgroonga (tags pgroonga.varchar_array_term_search_ops_v2);
ERROR:  operator class "pgroonga.varchar_array_term_search_ops_v2" does not exist for access method "pgroonga"
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT title, tags
  FROM memos
 WHERE tags %% 'Groonga';
                    QUERY PLAN                    
--------------------------------------------------
 Seq Scan on memos
   Filter: (tags %% 'Groonga'::character varying)
(2 rows)

SELECT title, tags
  FROM memos
 WHERE tags %% 'Groonga';
  title   |         tags         
----------+----------------------
 Groonga  | {Groonga}
 PGroonga | {PostgreSQL,Groonga}
(2 rows)

DROP TABLE memos;
DROP TABLE
```

The result of downgrade test:

```
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE TO '\''3.2.5'\'';'
ALTER EXTENSION pgroonga UPDATE TO '3.2.5';
ALTER EXTENSION
+ sudo dnf install -y postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64
Last metadata expiration check: 0:00:33 ago on Wed Feb  5 05:08:15 2025.
Dependencies resolved.
==========================================================================================================================================================================
 Package                                            Architecture                   Version                                Repository                                 Size
==========================================================================================================================================================================
Downgrading:
 postgresql17-pgdg-pgroonga                         x86_64                         3.2.5-1.el9                            groonga-almalinux                         768 k

Transaction Summary
==========================================================================================================================================================================
Downgrade  1 Package

Total download size: 768 k
Downloading Packages:
postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64.rpm                                                                                         1.1 MB/s | 768 kB     00:00    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                     1.1 MB/s | 768 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                  1/1 
  Downgrading      : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    2/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    1/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    2/2 

Downgraded:
  postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                           

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE memos (
  title text,
  tags varchar(1023)[]
);
CREATE TABLE
INSERT INTO memos VALUES ('PostgreSQL', ARRAY['PostgreSQL']);
INSERT 0 1
INSERT INTO memos VALUES ('Groonga', ARRAY['Groonga']);
INSERT 0 1
INSERT INTO memos VALUES ('PGroonga', ARRAY['PostgreSQL', 'Groonga']);
INSERT 0 1
CREATE INDEX pgroonga_memos_index ON memos
  USING pgroonga (tags pgroonga.varchar_array_term_search_ops_v2);
CREATE INDEX
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT title, tags
  FROM memos
 WHERE tags %% 'Groonga';
                      QUERY PLAN                      
------------------------------------------------------
 Index Scan using pgroonga_memos_index on memos
   Index Cond: (tags %% 'Groonga'::character varying)
(2 rows)

SELECT title, tags
  FROM memos
 WHERE tags %% 'Groonga';
  title   |         tags         
----------+----------------------
 Groonga  | {Groonga}
 PGroonga | {PostgreSQL,Groonga}
(2 rows)

DROP TABLE memos;
DROP TABLE
```