pgroonga: remov pgroonga.varchar_regexp_ops_v2 operator class (#679)
GitHub: GH-647

This is part of the task of remove "pgroonga" schema. It's deprecated
since PGroonga 2.
This is incompatible with PGroonga 3.x or earlier.

---

The result of upgrade test:

```
+ sudo dnf install -y /host/almalinux/9/x86_64/Packages/postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64.rpm
Last metadata expiration check: 0:00:34 ago on Wed Feb  5 05:23:59 2025.
Dependencies resolved.
==========================================================================================================================================================================
 Package                                              Architecture                     Version                               Repository                              Size
==========================================================================================================================================================================
Upgrading:
 postgresql17-pgdg-pgroonga                           x86_64                           4.0.0-1.el9                           @commandline                           775 k

Transaction Summary
==========================================================================================================================================================================
Upgrade  1 Package

Total size: 775 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                  1/1 
  Upgrading        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    2/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    1/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    2/2 

Upgraded:
  postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                           

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE;'
ALTER EXTENSION pgroonga UPDATE;
ALTER EXTENSION
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE memos (
  id integer,
  content varchar(256)
);
CREATE TABLE
INSERT INTO memos VALUES (1, 'PostgreSQL is a RDBMS.');
INSERT 0 1
INSERT INTO memos VALUES (2, 'Groonga is fast full text search engine.');
INSERT 0 1
INSERT INTO memos VALUES (3, 'PGroonga is a PostgreSQL extension that uses Groonga.');
INSERT 0 1
CREATE INDEX grnindex ON memos
  USING pgroonga (content pgroonga.varchar_regexp_ops_v2);
ERROR:  operator class "pgroonga.varchar_regexp_ops_v2" does not exist for access method "pgroonga"
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT id, content
  FROM memos
 WHERE content @~ '\Agroonga';
                      QUERY PLAN                       
-------------------------------------------------------
 Seq Scan on memos
   Filter: (content @~ '\Agroonga'::character varying)
(2 rows)

SELECT id, content
  FROM memos
 WHERE content @~ '\Agroonga';
 id |                 content                  
----+------------------------------------------
  2 | Groonga is fast full text search engine.
(1 row)

DROP TABLE memos;
DROP TABLE
```

The result of downgrade test:

```
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE TO '\''3.2.5'\'';'
ALTER EXTENSION pgroonga UPDATE TO '3.2.5';
ALTER EXTENSION
+ sudo dnf install -y postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64
Last metadata expiration check: 0:00:34 ago on Wed Feb  5 05:23:59 2025.
Dependencies resolved.
==========================================================================================================================================================================
 Package                                            Architecture                   Version                                Repository                                 Size
==========================================================================================================================================================================
Downgrading:
 postgresql17-pgdg-pgroonga                         x86_64                         3.2.5-1.el9                            groonga-almalinux                         768 k

Transaction Summary
==========================================================================================================================================================================
Downgrade  1 Package

Total download size: 768 k
Downloading Packages:
postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64.rpm                                                                                         935 kB/s | 768 kB     00:00    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                     932 kB/s | 768 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                  1/1 
  Downgrading      : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    2/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    1/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    2/2 

Downgraded:
  postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                           

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE memos (
  id integer,
  content varchar(256)
);
CREATE TABLE
INSERT INTO memos VALUES (1, 'PostgreSQL is a RDBMS.');
INSERT 0 1
INSERT INTO memos VALUES (2, 'Groonga is fast full text search engine.');
INSERT 0 1
INSERT INTO memos VALUES (3, 'PGroonga is a PostgreSQL extension that uses Groonga.');
INSERT 0 1
CREATE INDEX grnindex ON memos
  USING pgroonga (content pgroonga.varchar_regexp_ops_v2);
CREATE INDEX
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT id, content
  FROM memos
 WHERE content @~ '\Agroonga';
                        QUERY PLAN                         
-----------------------------------------------------------
 Index Scan using grnindex on memos
   Index Cond: (content @~ '\Agroonga'::character varying)
(2 rows)

SELECT id, content
  FROM memos
 WHERE content @~ '\Agroonga';
 id |                 content                  
----+------------------------------------------
  2 | Groonga is fast full text search engine.
(1 row)

DROP TABLE memos;
DROP TABLE
```