Fix a bug that removed table may be referred
GitHub: fix GH-90, fix GH-117

PGroonga doesn't close internal Groonga tables/indexes explicitly. If
other process such as AUTO VACUUM process removes unused Groonga
tables/indexes, long life connections may still refer removed Groonga
tables/indexes.

For example, the following scenario may refer removed Groonga
tables/indexes:

1. Connection1: CREATE INDEX A
2. Connection1: Groonga object A' (ID: 1000) is created
3. Connection2: REINDEX A
4. Connection2: (Groonga object A' (ID: 1000) isn't removed yet)
5. Connection2: Groonga object A'' (ID: 1001) is created
6. Connection3: AUTO VACUUM
7. Connection3: Groonga object A' (ID: 1000) is removed
8. Connection2: REINDEX A
9. Connection2: Groonga object A''' (ID: 1000) is created (ID is reused)
10. Connection1: SELECT * FROM A WHERE ...
    (Groonga object A' (ID: 1000) is still used not Groonga object A''')

If this is occurred when INSERT, the following error is raised:

    ERROR:  pgroonga: [insert] failed to add a record: <75300883>:
    [table][add][hash] failed to add:
     #<key "\u0013\u0000}\u0004\u0000\u0000\u0000\u0000"
       table:#<hash Sources17192 key:ShortText>>

This change fixes this problem by unmapping all Groonga objects after
VACUUM is happened.

Reported by Daisuke Ando. Thanks!!!
Reported by Raphael Gaschignard. Thanks!!!