data: remove pgroonga.text_array_full_text_search_ops operator class (#654)
GitHub: GH-647

This is part of the task of remove "pgroonga" schema. It's deprecated
since PGroonga 2.
This is incompatible with PGroonga 3.x or earlier.


Result of upgrade test:

```
====================================================================================================================================================================================================================
 Package                                                        Architecture                               Version                                           Repository                                        Size
====================================================================================================================================================================================================================
Upgrading:
 postgresql17-pgdg-pgroonga                                     x86_64                                     4.0.0-1.el9                                       @commandline                                     768 k

Transaction Summary
====================================================================================================================================================================================================================
Upgrade  1 Package

Total size: 768 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                            1/1 
  Upgrading        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                              1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                              2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                              2/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                              1/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                              2/2 

Upgraded:
  postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                                                     

Complete!
ALTER EXTENSION
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
ERROR:  operator class "pgroonga.text_array_full_text_search_ops" does not exist for access method "pgroonga"
SET
SET
SET
               QUERY PLAN                
-----------------------------------------
 Seq Scan on memos
   Filter: (contents &@ 'Groonga'::text)
(2 rows)
```

Result of downgrade test

```
====================================================================================================================================================================================================================
 Package                                                                Architecture                           Version                                      Repository                                         Size
====================================================================================================================================================================================================================
Installing:
 postgresql17-pgdg-pgroonga-debugsource                                 x86_64                                 3.2.5-1.el9                                  groonga-almalinux                                 117 k

Transaction Summary
====================================================================================================================================================================================================================
Install  1 Package

Total download size: 117 k
Installed size: 704 k
Downloading Packages:
postgresql17-pgdg-pgroonga-debugsource-3.2.5-1.el9.x86_64.rpm                                                                                                                       249 kB/s | 117 kB     00:00    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                               248 kB/s | 117 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                            1/1 
  Installing       : postgresql17-pgdg-pgroonga-debugsource-3.2.5-1.el9.x86_64                                                                                                                                  1/1 
  Verifying        : postgresql17-pgdg-pgroonga-debugsource-3.2.5-1.el9.x86_64                                                                                                                                  1/1 

Installed:
  postgresql17-pgdg-pgroonga-debugsource-3.2.5-1.el9.x86_64                                                                                                                                                         

Complete!
ALTER EXTENSION
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
CREATE INDEX
SET
SET
SET
                   QUERY PLAN                   
------------------------------------------------
 Index Scan using pgroonga_memos_index on memos
   Index Cond: (contents &@ 'Groonga'::text)
(2 rows)
```