pgroonga: remove pgroonga.jsonb_ops_v2 operator class (#677)
GitHub: GH-647

This is part of the task of remove "pgroonga" schema. It's deprecated
since PGroonga 2.
This is incompatible with PGroonga 3.x or earlier.

---

The result of upgrade test

```
+ sudo dnf install -y /host/almalinux/9/x86_64/Packages/postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64.rpm
Last metadata expiration check: 0:00:37 ago on Wed Feb  5 03:13:41 2025.
Dependencies resolved.
==========================================================================================================================================================================
 Package                                              Architecture                     Version                               Repository                              Size
==========================================================================================================================================================================
Upgrading:
 postgresql17-pgdg-pgroonga                           x86_64                           4.0.0-1.el9                           @commandline                           768 k

Transaction Summary
==========================================================================================================================================================================
Upgrade  1 Package

Total size: 768 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                  1/1 
  Upgrading        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    2/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    1/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    2/2 

Upgraded:
  postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                           

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE;'
ALTER EXTENSION pgroonga UPDATE;
ALTER EXTENSION
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE fruits (
  id int,
  items jsonb
);
CREATE TABLE
INSERT INTO fruits VALUES (1, '["apple"]');
INSERT 0 1
INSERT INTO fruits VALUES (2, '["banana", "apple"]');
INSERT 0 1
INSERT INTO fruits VALUES (3, '["peach"]');
INSERT 0 1
CREATE INDEX pgroonga_index ON fruits
  USING pgroonga (items pgroonga.jsonb_ops_v2);
ERROR:  operator class "pgroonga.jsonb_ops_v2" does not exist for access method "pgroonga"
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT id, items
  FROM fruits
 WHERE items &? 'banana OR peach'
 ORDER BY id;
                     QUERY PLAN                     
----------------------------------------------------
 Sort
   Sort Key: id
   ->  Seq Scan on fruits
         Filter: (items &? 'banana OR peach'::text)
(4 rows)

SELECT id, items
  FROM fruits
 WHERE items &? 'banana OR peach'
 ORDER BY id;
 id |        items        
----+---------------------
  2 | ["banana", "apple"]
  3 | ["peach"]
(2 rows)

DROP TABLE fruits;
DROP TABLE
```

The result of downgrade test:

```
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE TO '\''3.2.5'\'';'
ALTER EXTENSION pgroonga UPDATE TO '3.2.5';
ALTER EXTENSION
+ sudo dnf install -y postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64
Last metadata expiration check: 0:00:38 ago on Wed Feb  5 03:13:41 2025.
Dependencies resolved.
==========================================================================================================================================================================
 Package                                            Architecture                   Version                                Repository                                 Size
==========================================================================================================================================================================
Downgrading:
 postgresql17-pgdg-pgroonga                         x86_64                         3.2.5-1.el9                            groonga-almalinux                         768 k

Transaction Summary
==========================================================================================================================================================================
Downgrade  1 Package

Total download size: 768 k
Downloading Packages:
postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64.rpm                                                                                         845 kB/s | 768 kB     00:00    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                     843 kB/s | 768 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                  1/1 
  Downgrading      : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    2/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                    1/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                    2/2 

Downgraded:
  postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                           

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE fruits (
  id int,
  items jsonb
);
CREATE TABLE
INSERT INTO fruits VALUES (1, '["apple"]');
INSERT 0 1
INSERT INTO fruits VALUES (2, '["banana", "apple"]');
INSERT 0 1
INSERT INTO fruits VALUES (3, '["peach"]');
INSERT 0 1
CREATE INDEX pgroonga_index ON fruits
  USING pgroonga (items pgroonga.jsonb_ops_v2);
CREATE INDEX
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT id, items
  FROM fruits
 WHERE items &? 'banana OR peach'
 ORDER BY id;
                       QUERY PLAN                       
--------------------------------------------------------
 Sort
   Sort Key: id
   ->  Index Scan using pgroonga_index on fruits
         Index Cond: (items &? 'banana OR peach'::text)
(4 rows)

SELECT id, items
  FROM fruits
 WHERE items &? 'banana OR peach'
 ORDER BY id;
 id |        items        
----+---------------------
  2 | ["banana", "apple"]
  3 | ["peach"]
(2 rows)

DROP TABLE fruits;
DROP TABLE
```