pgroonga: remove pgroonga.int4_ops operator class (#660)
GitHub: GH-647

This is part of the task of remove "pgroonga" schema. It's deprecated
since PGroonga 2.
This is incompatible with PGroonga 3.x or earlier.

---

Result of upgrade test:

```
+ sudo dnf install -y /host/almalinux/9/x86_64/Packages/postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64.rpm
Last metadata expiration check: 0:00:26 ago on Mon Feb  3 07:43:19 2025.
Dependencies resolved.
=============================================================================================================================================================================
 Package                                              Architecture                     Version                                  Repository                              Size
=============================================================================================================================================================================
Upgrading:
 postgresql17-pgdg-pgroonga                           x86_64                           4.0.0-1.el9                              @commandline                           768 k

Transaction Summary
=============================================================================================================================================================================
Upgrade  1 Package

Total size: 768 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                     1/1 
  Upgrading        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                       1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                       2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                       2/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                       1/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                       2/2 

Upgraded:
  postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                              

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE;'
ALTER EXTENSION pgroonga UPDATE;
ALTER EXTENSION
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE numbers (
  number1 integer,
  number2 integer
);
CREATE TABLE
INSERT INTO numbers VALUES (2,  20);
INSERT 0 1
INSERT INTO numbers VALUES (7,  70);
INSERT 0 1
INSERT INTO numbers VALUES (6,  60);
INSERT 0 1
INSERT INTO numbers VALUES (4,  40);
INSERT 0 1
INSERT INTO numbers VALUES (5,  50);
INSERT 0 1
INSERT INTO numbers VALUES (8,  80);
INSERT 0 1
INSERT INTO numbers VALUES (1,  10);
INSERT 0 1
INSERT INTO numbers VALUES (10, 100);
INSERT 0 1
INSERT INTO numbers VALUES (3,  30);
INSERT 0 1
INSERT INTO numbers VALUES (9,  90);
INSERT 0 1
CREATE INDEX grnindex ON numbers
  USING pgroonga (number1 pgroonga.int4_ops,
                  number2 pgroonga.int4_ops);
ERROR:  operator class "pgroonga.int4_ops" does not exist for access method "pgroonga"
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT number1, number2
  FROM numbers
 WHERE number1 >= 3 AND number2 >= 50
 ORDER BY number1 ASC;
                      QUERY PLAN                      
------------------------------------------------------
 Sort
   Sort Key: number1
   ->  Seq Scan on numbers
         Filter: ((number1 >= 3) AND (number2 >= 50))
(4 rows)

SELECT number1, number2
  FROM numbers
 WHERE number1 >= 3 AND number2 >= 50
 ORDER BY number1 ASC;
 number1 | number2 
---------+---------
       5 |      50
       6 |      60
       7 |      70
       8 |      80
       9 |      90
      10 |     100
(6 rows)

DROP TABLE numbers;
DROP TABLE
```

Result of downgrade test:

```
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE TO '\''3.2.5'\'';'
ALTER EXTENSION pgroonga UPDATE TO '3.2.5';
ALTER EXTENSION
+ sudo dnf install -y postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64
Last metadata expiration check: 0:00:26 ago on Mon Feb  3 07:43:19 2025.
Dependencies resolved.
=============================================================================================================================================================================
 Package                                             Architecture                    Version                                Repository                                  Size
=============================================================================================================================================================================
Downgrading:
 postgresql17-pgdg-pgroonga                          x86_64                          3.2.5-1.el9                            groonga-almalinux                          768 k

Transaction Summary
=============================================================================================================================================================================
Downgrade  1 Package

Total download size: 768 k
Downloading Packages:
postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64.rpm                                                                                            904 kB/s | 768 kB     00:00    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                        901 kB/s | 768 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                     1/1 
  Downgrading      : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                       1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                       2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                       2/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                       1/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                       2/2 

Downgraded:
  postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                              

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE numbers (
  number1 integer,
  number2 integer
);
CREATE TABLE
INSERT INTO numbers VALUES (2,  20);
INSERT 0 1
INSERT INTO numbers VALUES (7,  70);
INSERT 0 1
INSERT INTO numbers VALUES (6,  60);
INSERT 0 1
INSERT INTO numbers VALUES (4,  40);
INSERT 0 1
INSERT INTO numbers VALUES (5,  50);
INSERT 0 1
INSERT INTO numbers VALUES (8,  80);
INSERT 0 1
INSERT INTO numbers VALUES (1,  10);
INSERT 0 1
INSERT INTO numbers VALUES (10, 100);
INSERT 0 1
INSERT INTO numbers VALUES (3,  30);
INSERT 0 1
INSERT INTO numbers VALUES (9,  90);
INSERT 0 1
CREATE INDEX grnindex ON numbers
  USING pgroonga (number1 pgroonga.int4_ops,
                  number2 pgroonga.int4_ops);
CREATE INDEX
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT number1, number2
  FROM numbers
 WHERE number1 >= 3 AND number2 >= 50
 ORDER BY number1 ASC;
                     QUERY PLAN                     
----------------------------------------------------
 Index Scan using grnindex on numbers
   Index Cond: ((number1 >= 3) AND (number2 >= 50))
(2 rows)

SELECT number1, number2
  FROM numbers
 WHERE number1 >= 3 AND number2 >= 50
 ORDER BY number1 ASC;
 number1 | number2 
---------+---------
       5 |      50
       6 |      60
       7 |      70
       8 |      80
       9 |      90
      10 |     100
(6 rows)

DROP TABLE numbers;
DROP TABLE
```