packages apt: use --platform=linux/arm64 explicitly (#568)
Because of build failure.

Example of error:

```
ERROR: failed to solve: arm64v8/ubuntu:focal: failed to resolve source metadata for docker.io/arm64v8/ubuntu:focal: no match for platform in manifest: not found
```