Revert "specify prefix because we don't want to use `sudo` access"
This reverts commit 1d3d10c7281b047a3424c6ad9a12cf77fcdd8246.
It's because we still got the following errors.

```
Run meson install -C pgroonga.build
ninja: Entering directory `/home/runner/work/pgroonga/pgroonga/pgroonga.build'
ninja: no work to do.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 873, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 553, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 750, in install_targets
    file_copied = self.do_copyfile(fname, outname, makedirs=(dm, outdir))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 430, in do_copyfile
    self.copy2(from_file, to_file)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 327, in copy2
    shutil.copy2(*args, **kwargs)
  File "/usr/lib/python3.12/shutil.py", line 475, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.12/shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/lib/postgresql/13/lib/pgroonga_check.so'
Installing pgroonga_check.so to /usr/lib/postgresql/13/lib

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
Error: Process completed with exit code 13.
```