postgresql-19: use `Node *' instead of `fmNodePtr` (#795)
`fmNodePtr` was removed:

https://github.com/postgres/postgres/commit/4bd91912987d794c48dd4ba4c337906bd23759be


https://github.com/pgroonga/pgroonga/actions/runs/17998815903/job/51203377015#step:8:43

```text
In file included from ../pgroonga/src/pgroonga.h:9,
                 from ../pgroonga/src/pgrn-pg.c:1:
../pgroonga/src/pgrn-pg.c: In function ‘PGrnPGHavePreparedTransaction’:
../pgroonga/src/pgrn-pg.c:299:65: error: ‘fmNodePtr’ undeclared (first use in this function)
  299 |                         *fcinfo, &flinfo, 0, InvalidOid, NULL, (fmNodePtr) &rsinfo);
      |                                                                 ^~~~~~~~~
```