pgroonga: remove pgroonga.timestamptz_ops operator class (#667)
GitHub: GH-647

This is part of the task of remove "pgroonga" schema. It's deprecated
since PGroonga 2.
This is incompatible with PGroonga 3.x or earlier.

---

The result of upgrade test:

```
+ sudo dnf install -y /host/almalinux/9/x86_64/Packages/postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64.rpm
Last metadata expiration check: 0:00:30 ago on Tue Feb  4 13:08:04 2025.
Dependencies resolved.
========================================================================================================================================================================================================
 Package                                                     Architecture                            Version                                        Repository                                     Size
========================================================================================================================================================================================================
Upgrading:
 postgresql17-pgdg-pgroonga                                  x86_64                                  4.0.0-1.el9                                    @commandline                                  768 k

Transaction Summary
========================================================================================================================================================================================================
Upgrade  1 Package

Total size: 768 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                1/1 
  Upgrading        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                  1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                  2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                  2/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                  1/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                  2/2 

Upgraded:
  postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                                         

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE;'
ALTER EXTENSION pgroonga UPDATE;
ALTER EXTENSION
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE logs (
  created_at timestamp with time zone
);
CREATE TABLE
INSERT INTO logs VALUES ('2015-02-14 10:44:10+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:09+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:02+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:04+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:01+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:05+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:07+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:06+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:03+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:08+09:00');
INSERT 0 1
CREATE INDEX pgroonga_index ON logs
  USING pgroonga (created_at pgroonga.timestamptz_ops);
ERROR:  operator class "pgroonga.timestamptz_ops" does not exist for access method "pgroonga"
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT created_at
  FROM logs
 WHERE created_at BETWEEN '2015-02-14 10:44:03+09:00' AND '2015-02-14 10:44:09+09:00'
 ORDER BY created_at ASC;
                                                                         QUERY PLAN                                                                          
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort
   Sort Key: created_at
   ->  Seq Scan on logs
         Filter: ((created_at >= '2015-02-14 01:44:03+00'::timestamp with time zone) AND (created_at <= '2015-02-14 01:44:09+00'::timestamp with time zone))
(4 rows)

SELECT created_at
  FROM logs
 WHERE created_at BETWEEN '2015-02-14 10:44:03+09:00' AND '2015-02-14 10:44:09+09:00'
 ORDER BY created_at ASC;
       created_at       
------------------------
 2015-02-14 01:44:03+00
 2015-02-14 01:44:04+00
 2015-02-14 01:44:05+00
 2015-02-14 01:44:06+00
 2015-02-14 01:44:07+00
 2015-02-14 01:44:08+00
 2015-02-14 01:44:09+00
(7 rows)

DROP TABLE logs;
DROP TABLE
```

The result of downgrade test:

```
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE TO '\''3.2.5'\'';'
ALTER EXTENSION pgroonga UPDATE TO '3.2.5';
ALTER EXTENSION
+ sudo dnf install -y postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64
Last metadata expiration check: 0:00:31 ago on Tue Feb  4 13:08:04 2025.
Dependencies resolved.
========================================================================================================================================================================================================
 Package                                                    Architecture                           Version                                      Repository                                         Size
========================================================================================================================================================================================================
Downgrading:
 postgresql17-pgdg-pgroonga                                 x86_64                                 3.2.5-1.el9                                  groonga-almalinux                                 768 k

Transaction Summary
========================================================================================================================================================================================================
Downgrade  1 Package

Total download size: 768 k
Downloading Packages:
postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64.rpm                                                                                                                       959 kB/s | 768 kB     00:00    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                   957 kB/s | 768 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                1/1 
  Downgrading      : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                  1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                  2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                  2/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                  1/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                  2/2 

Downgraded:
  postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                                         

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE logs (
  created_at timestamp with time zone
);
CREATE TABLE
INSERT INTO logs VALUES ('2015-02-14 10:44:10+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:09+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:02+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:04+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:01+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:05+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:07+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:06+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:03+09:00');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:08+09:00');
INSERT 0 1
CREATE INDEX pgroonga_index ON logs
  USING pgroonga (created_at pgroonga.timestamptz_ops);
CREATE INDEX
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT created_at
  FROM logs
 WHERE created_at BETWEEN '2015-02-14 10:44:03+09:00' AND '2015-02-14 10:44:09+09:00'
 ORDER BY created_at ASC;
                                                                        QUERY PLAN                                                                         
-----------------------------------------------------------------------------------------------------------------------------------------------------------
 Index Scan using pgroonga_index on logs
   Index Cond: ((created_at >= '2015-02-14 01:44:03+00'::timestamp with time zone) AND (created_at <= '2015-02-14 01:44:09+00'::timestamp with time zone))
(2 rows)

SELECT created_at
  FROM logs
 WHERE created_at BETWEEN '2015-02-14 10:44:03+09:00' AND '2015-02-14 10:44:09+09:00'
 ORDER BY created_at ASC;
       created_at       
------------------------
 2015-02-14 01:44:03+00
 2015-02-14 01:44:04+00
 2015-02-14 01:44:05+00
 2015-02-14 01:44:06+00
 2015-02-14 01:44:07+00
 2015-02-14 01:44:08+00
 2015-02-14 01:44:09+00
(7 rows)

DROP TABLE logs;
DROP TABLE
```