windows: fix VC_PRESIX to build on the latest Visual Studio
VC_PREFIX is changed since Visual Studio 2026 from "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC" to "VC_PREFIX=C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC".

This modification resolve the following errors:

```
In file included from D:/a/pgroonga/groonga/vendor/mecab-0.996/src/char_property.h:8,
                 from D:/a/pgroonga/groonga/vendor/mecab-0.996/src/char_property.cpp:11:
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:67:3: error: 'HANDLE' does not name a type [-Wtemplate-body]
   67 |   HANDLE hFile;
      |   ^~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:68:3: error: 'HANDLE' does not name a type [-Wtemplate-body]
   68 |   HANDLE hMap;
      |   ^~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h: In member function 'bool MeCab::Mmap<T>::open(const char*, const char*)':
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:96:15: error: 'GENERIC_READ' was not declared in this scope [-Wtemplate-body]
   96 |       mode1 = GENERIC_READ;
      |               ^~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:97:15: error: 'PAGE_READONLY' was not declared in this scope [-Wtemplate-body]
   97 |       mode2 = PAGE_READONLY;
      |               ^~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:98:15: error: 'FILE_MAP_READ' was not declared in this scope [-Wtemplate-body]
   98 |       mode3 = FILE_MAP_READ;
      |               ^~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:100:15: error: 'GENERIC_READ' was not declared in this scope [-Wtemplate-body]
  100 |       mode1 = GENERIC_READ | GENERIC_WRITE;
      |               ^~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:100:30: error: 'GENERIC_WRITE' was not declared in this scope [-Wtemplate-body]
  100 |       mode1 = GENERIC_READ | GENERIC_WRITE;
      |                              ^~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:101:15: error: 'PAGE_READWRITE' was not declared in this scope [-Wtemplate-body]
  101 |       mode2 = PAGE_READWRITE;
      |               ^~~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:102:15: error: 'FILE_MAP_ALL_ACCESS' was not declared in this scope [-Wtemplate-body]
  102 |       mode3 = FILE_MAP_ALL_ACCESS;
      |               ^~~~~~~~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:107:5: error: 'hFile' was not declared in this scope [-Wtemplate-body]
  107 |     hFile = ::CreateFileW(WPATH(filename), mode1, FILE_SHARE_READ, 0,
      |     ^~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:107:15: error: '::CreateFileW' has not been declared [-Wtemplate-body]
  107 |     hFile = ::CreateFileW(WPATH(filename), mode1, FILE_SHARE_READ, 0,
      |               ^~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:107:51: error: 'FILE_SHARE_READ' was not declared in this scope [-Wtemplate-body]
  107 |     hFile = ::CreateFileW(WPATH(filename), mode1, FILE_SHARE_READ, 0,
      |                                                   ^~~~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:108:27: error: 'OPEN_EXISTING' was not declared in this scope [-Wtemplate-body]
  108 |                           OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, 0);
      |                           ^~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:108:42: error: 'FILE_ATTRIBUTE_NORMAL' was not declared in this scope [-Wtemplate-body]
  108 |                           OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, 0);
      |                                          ^~~~~~~~~~~~~~~~~~~~~
In file included from D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:50:
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:109:26: error: 'INVALID_HANDLE_VALUE' was not declared in this scope [-Wtemplate-body]
  109 |     CHECK_FALSE(hFile != INVALID_HANDLE_VALUE)
      |                          ^~~~~~~~~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/common.h:126:6: note: in definition of macro 'CHECK_FALSE'
  126 |  if (condition) {} else return \
      |      ^~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:112:16: error: '::GetFileSize' has not been declared [-Wtemplate-body]
  112 |     length = ::GetFileSize(hFile, 0);
      |                ^~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:114:5: error: 'hMap' was not declared in this scope [-Wtemplate-body]
  114 |     hMap = ::CreateFileMapping(hFile, 0, mode2, 0, 0, 0);
      |     ^~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:114:14: error: '::CreateFileMapping' has not been declared [-Wtemplate-body]
  114 |     hMap = ::CreateFileMapping(hFile, 0, mode2, 0, 0, 0);
      |              ^~~~~~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:117:36: error: '::MapViewOfFile' has not been declared [-Wtemplate-body]
  117 |     text = reinterpret_cast<T *>(::MapViewOfFile(hMap, mode3, 0, 0, 0));
      |                                    ^~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h: In member function 'void MeCab::Mmap<T>::close()':
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:124:19: error: '::UnmapViewOfFile' has not been declared [-Wtemplate-body]
  124 |     if (text) { ::UnmapViewOfFile(text); }
      |                   ^~~~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:125:9: error: 'hFile' was not declared in this scope [-Wtemplate-body]
  125 |     if (hFile != INVALID_HANDLE_VALUE) {
      |         ^~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:125:18: error: 'INVALID_HANDLE_VALUE' was not declared in this scope [-Wtemplate-body]
  125 |     if (hFile != INVALID_HANDLE_VALUE) {
      |                  ^~~~~~~~~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:126:9: error: '::CloseHandle' has not been declared [-Wtemplate-body]
  126 |       ::CloseHandle(hFile);
      |         ^~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:129:9: error: 'hMap' was not declared in this scope [-Wtemplate-body]
  129 |     if (hMap) {
      |         ^~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:130:9: error: '::CloseHandle' has not been declared [-Wtemplate-body]
  130 |       ::CloseHandle(hMap);
      |         ^~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h: In constructor 'MeCab::Mmap<T>::Mmap()':
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:136:20: error: class 'MeCab::Mmap<T>' does not have any field named 'hFile' [-Wtemplate-body]
  136 |   Mmap(): text(0), hFile(INVALID_HANDLE_VALUE), hMap(0) {}
      |                    ^~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:136:26: error: 'INVALID_HANDLE_VALUE' was not declared in this scope [-Wtemplate-body]
  136 |   Mmap(): text(0), hFile(INVALID_HANDLE_VALUE), hMap(0) {}
      |                          ^~~~~~~~~~~~~~~~~~~~
D:/a/pgroonga/groonga/vendor/mecab-0.996/src/mmap.h:136:49: error: class 'MeCab::Mmap<T>' does not have any field named 'hMap' [-Wtemplate-body]
  136 |   Mmap(): text(0), hFile(INVALID_HANDLE_VALUE), hMap(0) {}
      |                                                 ^~~~
```