Remove unnecessary pgroonga_condition() definitions (#525)
If you upgrade to 3.2.1 with PGroonga already installed, you get the
following error.

```
WHERE content &@~ pgroonga_condition('PGroonga');
                           ^
HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
```

The log also reports the following error.

```
ERROR:  function pgroonga_condition(unknown) is not unique at character 84
```

This is due to a bug in `data/pgroonga--3.2.0--3.2.1.sql` where two
pgroonga_condition() were defined.
Therefore, the unnecessary pgroonga_condition() definition was removed.