pgroonga: remove pgroonga.timestamp_ops operator class (#666)
GitHub: GH-647

This is part of the task of remove "pgroonga" schema. It's deprecated
since PGroonga 2.
This is incompatible with PGroonga 3.x or earlier.

---

The result of upgrade test:

```
+ sudo dnf install -y /host/almalinux/9/x86_64/Packages/postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64.rpm
Last metadata expiration check: 0:00:22 ago on Tue Feb  4 12:58:05 2025.
Dependencies resolved.
========================================================================================================================================================================================================
 Package                                                     Architecture                            Version                                        Repository                                     Size
========================================================================================================================================================================================================
Upgrading:
 postgresql17-pgdg-pgroonga                                  x86_64                                  4.0.0-1.el9                                    @commandline                                  768 k

Transaction Summary
========================================================================================================================================================================================================
Upgrade  1 Package

Total size: 768 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                1/1 
  Upgrading        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                  1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                  2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                  2/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                  1/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                  2/2 

Upgraded:
  postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                                         

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE;'
ALTER EXTENSION pgroonga UPDATE;
ALTER EXTENSION
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE logs (
  created_at timestamp
);
CREATE TABLE
INSERT INTO logs VALUES ('2015-02-14 10:44:10');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:09');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:02');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:04');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:01');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:05');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:07');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:06');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:03');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:08');
INSERT 0 1
CREATE INDEX pgroonga_index ON logs
  USING pgroonga (created_at pgroonga.timestamp_ops);
ERROR:  operator class "pgroonga.timestamp_ops" does not exist for access method "pgroonga"
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT created_at
  FROM logs
 WHERE created_at BETWEEN '2015-02-14 10:44:03' AND '2015-02-14 10:44:09'
 ORDER BY created_at ASC;
                                                                         QUERY PLAN                                                                          
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort
   Sort Key: created_at
   ->  Seq Scan on logs
         Filter: ((created_at >= '2015-02-14 10:44:03'::timestamp without time zone) AND (created_at <= '2015-02-14 10:44:09'::timestamp without time zone))
(4 rows)

SELECT created_at
  FROM logs
 WHERE created_at BETWEEN '2015-02-14 10:44:03' AND '2015-02-14 10:44:09'
 ORDER BY created_at ASC;
     created_at      
---------------------
 2015-02-14 10:44:03
 2015-02-14 10:44:04
 2015-02-14 10:44:05
 2015-02-14 10:44:06
 2015-02-14 10:44:07
 2015-02-14 10:44:08
 2015-02-14 10:44:09
(7 rows)

DROP TABLE logs;
DROP TABLE
```

The result of downgrade test:

```
+ sudo -u postgres -H psql --echo-all -d pgroonga_test --command 'ALTER EXTENSION pgroonga UPDATE TO '\''3.2.5'\'';'
ALTER EXTENSION pgroonga UPDATE TO '3.2.5';
ALTER EXTENSION
+ sudo dnf install -y postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64
Last metadata expiration check: 0:00:23 ago on Tue Feb  4 12:58:05 2025.
Dependencies resolved.
========================================================================================================================================================================================================
 Package                                                    Architecture                           Version                                      Repository                                         Size
========================================================================================================================================================================================================
Downgrading:
 postgresql17-pgdg-pgroonga                                 x86_64                                 3.2.5-1.el9                                  groonga-almalinux                                 768 k

Transaction Summary
========================================================================================================================================================================================================
Downgrade  1 Package

Total download size: 768 k
Downloading Packages:
postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64.rpm                                                                                                                       646 kB/s | 768 kB     00:01    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                   645 kB/s | 768 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                1/1 
  Downgrading      : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                  1/2 
  Cleanup          : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                  2/2 
  Running scriptlet: postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                  2/2 
  Verifying        : postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                  1/2 
  Verifying        : postgresql17-pgdg-pgroonga-4.0.0-1.el9.x86_64                                                                                                                                  2/2 

Downgraded:
  postgresql17-pgdg-pgroonga-3.2.5-1.el9.x86_64                                                                                                                                                         

Complete!
+ sudo -u postgres -H psql --echo-all -d pgroonga_test
CREATE TABLE logs (
  created_at timestamp
);
CREATE TABLE
INSERT INTO logs VALUES ('2015-02-14 10:44:10');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:09');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:02');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:04');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:01');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:05');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:07');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:06');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:03');
INSERT 0 1
INSERT INTO logs VALUES ('2015-02-14 10:44:08');
INSERT 0 1
CREATE INDEX pgroonga_index ON logs
  USING pgroonga (created_at pgroonga.timestamp_ops);
CREATE INDEX
SET enable_seqscan = off;
SET
SET enable_indexscan = on;
SET
SET enable_bitmapscan = off;
SET
EXPLAIN (COSTS OFF)
SELECT created_at
  FROM logs
 WHERE created_at BETWEEN '2015-02-14 10:44:03' AND '2015-02-14 10:44:09'
 ORDER BY created_at ASC;
                                                                        QUERY PLAN                                                                         
-----------------------------------------------------------------------------------------------------------------------------------------------------------
 Index Scan using pgroonga_index on logs
   Index Cond: ((created_at >= '2015-02-14 10:44:03'::timestamp without time zone) AND (created_at <= '2015-02-14 10:44:09'::timestamp without time zone))
(2 rows)

SELECT created_at
  FROM logs
 WHERE created_at BETWEEN '2015-02-14 10:44:03' AND '2015-02-14 10:44:09'
 ORDER BY created_at ASC;
     created_at      
---------------------
 2015-02-14 10:44:03
 2015-02-14 10:44:04
 2015-02-14 10:44:05
 2015-02-14 10:44:06
 2015-02-14 10:44:07
 2015-02-14 10:44:08
 2015-02-14 10:44:09
(7 rows)

DROP TABLE logs;
DROP TABLE
```